using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WocForC_.Service;

namespace WocForC_.Models
{
    // C# code-behind

    // The data template is defined to display a Contact object (class definition shown below), and the text
    // displayed is bound to the Contact object's Name attribute.

    public class Contact
    {
        public string Name { get; private set; } = string.Empty;
        public string Path { get; private set; } = string.Empty;
        public Contact(string name, string path)
        {
            Name = name;
            Path = path;
        }
        public static async Task<ObservableCollection<Contact>> GetContactsAsync()
        {
            var contacts = new ObservableCollection<Contact>();
            var folders = await Historys.GetHistory();
            foreach (var folder in folders)
            {
                contacts.Add(new Contact(folder.Name, folder.Path));
            }
            return contacts;
        }
    }

    // The ItemsSource for the ListView is generated by a method of the Contact class called
    // GetContactsAsync().This method pulls data from an internal data source and creates
    // Contact objects from that data. Those Contact objects are placed in a collection
    // which is returned from the GetContactsAsync() function.

}
